### ISSUE TITLE
The position of the tooltip element is not centered when the body scrollbar is displayed.

### ISSUE THREAD

**Issue by Rudi-Batubara** [thednp/bootstrap.native#215]
I am using 

> Native Javascript for Bootstrap 4 [v2.0.23](https://github.com/thednp/bootstrap.native)

 and found all positions of tooltip element not really centered when body scrollbar is displayed. Is there a practical way to fix this bug?

**Bug preview :** 
![1](https://user-images.githubusercontent.com/10338643/40034066-6600ac3a-5825-11e8-8f48-283d7c2f5e5b.jpg)

**Fine preview:**
![2](https://user-images.githubusercontent.com/10338643/40034120-a90ba8ae-5825-11e8-83da-769ccadb89a0.jpg)

Could you please help me to fix this bug ?

**Comment by thednp** [comment]
Depends if the "issue" is an user-related issue or not. We would like to see some markup so I can make an idea.

**Comment by Rudi-Batubara** [comment]
This is my markup :

> `<li><a class="nav-link" href="#" id="dropdownCart" data-toggle="dropdown" data-persist="true" aria-haspopup="true" aria-expanded="false">
                    <svg version="1.1" class="icon-24 d-block" width="24" height="24" role="img" aria-label="nav-shop nav-shop-desc">
                        <title id="nav-shop">Shop</title>
                        <desc id="nav-shop-desc">Shopping icon</desc>
                        <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="{{ secure_asset('img/icons.svg') }}#shop"></use>
                    </svg>
                </a></li>`

**Comment by thednp** [comment]
@Rudi-Batubara why not make a codepen or fiddle so we can see this in a real world?

**Comment by duduik** [comment]
Similar issue, but when the scrollbar is not displayed.
https://jsfiddle.net/s17304Lf/2/

**Comment by thednp** [comment]
@duduik I can't explain that, have no idea how to fix that case.

**Comment by thednp** [comment]
@Rudi-Batubara I'm currently investigating that case and I cannot confirm that to be an issue. The issue @duduik posted is confirmed so far.

**Comment by duduik** [comment]
It works on https://jsfiddle.net/wcxkvL53/1/. 

But on a slightly different markup (the `button` wrapped with `div`), the issue appear again. https://jsfiddle.net/wcxkvL53/.

Thank you.

**Comment by thednp** [comment]
I suggest you stick to the previous markup, we can't check the entire document for a tooltip can we?

**Comment by thednp** [comment]
I would like to add an important comment on the issue. 

As we know the original plugin makes of the popper.js library to process the placement of Tooltip, Popover and Dropdown and I came to the conclusion that our 20-30 lines `styleTip()` utility may never be able to achieve the same effect as the third party library such as popper.js.

The most important thing is, our library was never designed to do every feature of the original jQuery plugins, especially this kind of [quirks with special markup](https://github.com/thednp/bootstrap.native/issues/215#issuecomment-513530516). This library provides a certain set of features in a way to enable long term maintenance, keeping the code in check on size and consistency.

Now I need to know @Rudi-Batubara is your original issue solved with latest code in the master branch?

**Comment by Rudi-Batubara** [comment]
the issue has been solved, the issue comes from my bad DOM structure. When I changed the structure of my DOM and fixed a number of styles, it worked well. Just like what @duduik  did.

Thank you, @thednp

I hope, in this new version it will be better

**Comment by Gruven** [comment]
@thednp the problem only partially solved. When inner div is from "91vh" to "99vh" it doesn't work as expected...
https://jsfiddle.net/Gruven/ejfpr21g/6/

**Comment by thednp** [comment]
@Gruven that issue is expected because we don't implement popper.js. 

I am open to any suggestion on how to reliably manage the vh based popover/tooltip target containers.

**Comment by Gruven** [comment]
@thednp this not about vh based containers. This bug appears when body height is close to the bottom of viewport.
https://jsfiddle.net/Gruven/ejfpr21g/7/
Try changing body height and you'll see.
Looks like tooltip changes its position too early.

**Comment by thednp** [comment]
@Gruven it's not a bug, it's a case not handled yet, that's why I say we're open to suggestions.

**Comment by Gruven** [comment]
@thednp do you know why rect from utils 
https://github.com/thednp/bootstrap.native/blob/92ccb118f28b5a125b8a95c6425accba893c717f/lib/V4/utils.js#L248
and rect from my custom script
```
const testBtn = document.getElementById('filter-collapse-button');
if (testBtn) {
  testBtn.addEventListener('mouseover', () => {
    console.log(testBtn['getBoundingClientRect']());
  });
}
```
returns different values when this case appears?
```
DOMRect { x: 1741, y: 80, width: 42, height: 38, top: 80, right: 1783, bottom: 118, left: 1741 }
DOMRect { x: 1729, y: 80, width: 42, height: 38, top: 80, right: 1771, bottom: 118, left: 1729 }
```

**Comment by Gruven** [comment]
@thednp success! It works! Please, add after this
https://github.com/thednp/bootstrap.native/blob/92ccb118f28b5a125b8a95c6425accba893c717f/lib/V4/tooltip-native.js#L80
this lines or similar
```
        tooltip['style']['left'] = '0';
        tooltip['style']['top'] = '0';
```

**Comment by thednp** [comment]
@Gruven the difference comes from two moments in time:

* first is the moment when user hovers the tooltip/popover target
* second is the moment when all calculation is done and we're ready to ship the markup to the DOM

For some reason, Tooltip component changes the values of the viewport like `offsetHeight` or `clientHeight` making it sometimes impossible to know if we're actually working with an overflow viewport or not.

About your suggestion, please make it clear what exactly is the suggested change, because I don't understand the need to set position for `top` and `left` to 0.

**Comment by Gruven** [comment]
@thednp as I understood:

1. Tooltip element creates
2. Tooltip appends to container
3. Rect calculating
4. Tooltip position changes

We need to set init position for tooltip between steps 2 and 3, because it takes some place within container, so scroll appears on some moment.

**Comment by thednp** [comment]
@Gruven not exactly, if you read the code, you will actually find:

* tooltip is created
* tooltip is appended to the DOM
* tooltip is positioned relative to it's target
* tooltip is displayed

**Comment by Gruven** [comment]
@thednp no, after appending it is already displayed. After this line
https://github.com/thednp/bootstrap.native/blob/92ccb118f28b5a125b8a95c6425accba893c717f/lib/V4/tooltip-native.js#L120
Tooltip appears at the bottom of the container with "position: absolute", "display: block" and "opacity: 0". (screenshots - https://send.firefox.com/download/2d0e1142c769ab83/#cEniBIy_X_V3vBMYPs_28g )
So let's see the next line
https://github.com/thednp/bootstrap.native/blob/92ccb118f28b5a125b8a95c6425accba893c717f/lib/V4/tooltip-native.js#L121
And then to the next
https://github.com/thednp/bootstrap.native/blob/92ccb118f28b5a125b8a95c6425accba893c717f/lib/V4/tooltip-native.js#L97
This sent us to var declaration, where rect is calculating
https://github.com/thednp/bootstrap.native/blob/92ccb118f28b5a125b8a95c6425accba893c717f/lib/V4/utils.js#L248
By that time tooltip already appended and displayed with "opacity: 0". Scroll is displayed too. So we get wrong calculation of rect values.

**Comment by Gruven** [comment]
@thednp I think a better solution will be something like "left: -{tooltipOuterWidth}px" and "top: -{tooltipOuterHeight}px"

**Comment by thednp** [comment]
@Gruven I will try the first solution first, I think that makes alot more sense.

**Comment by thednp** [comment]
@Gruven @duduik @Rudi-Batubara please do a final test, we need to push a new build into the cloud as soon as we can.

**Comment by Gruven** [comment]
@thednp already done https://github.com/thednp/bootstrap.native/commit/145defd9a76b1f04b985600054566ba665dc5487#comments
Waiting @Rudi-Batubara

**Comment by thednp** [comment]
Alright guys we're good. This is now 100% closed.
