### ISSUE TITLE
There is a serious problem with the relative positioning of the Popover when changing the container.

### ISSUE THREAD

**Issue by cvaize** [thednp/bootstrap.native#404]
The problem is, if you specify a container, the indent is still calculated from the document body. In the original bootstrap 5, the calculation is done correctly. In the original bootstrap 5, there is a problem with reinitialization. To see the problem, call this code on the page [http://thednp.github.io/bootstrap.native/v5.html](http://thednp.github.io/bootstrap.native/v5.html) and on the page [https://getbootstrap.com/docs/5.0/components/popovers/](https://getbootstrap.com/docs/5.0/components/popovers/).

```javascript
(function (){
    let lib = window.bootstrap || window.BSN;
    console.log(lib);

    let container = document.querySelector('main') || document.getElementById('use');
    container.innerHTML = '<div class="bd-intro">' +
        '<button id="test-popover" type="button" class="btn btn-lg btn-danger" data-bs-toggle="popover" title="Popover title" data-bs-content="And here\'s some amazing content. It\'s very engaging. Right?">Click to toggle popover</button>\n' +
        '</div>' + container.innerHTML;
    let element = document.querySelector('#test-popover');
    element.parentNode.style.position = 'relative';
    new lib.Popover(element, {container: element.parentNode, trigger: 'click'});
})();
```

![image](https://user-images.githubusercontent.com/26907947/107476008-db184780-6b96-11eb-8041-feb85f1bdaf5.png)
![image](https://user-images.githubusercontent.com/26907947/107476114-0bf87c80-6b97-11eb-8d30-a4d2e976699f.png)

**Comment by cvaize** [comment]
The same problem applies to Tooltip. Here is the code to check:
```javascript
(function (){
    let lib = window.bootstrap || window.BSN;
    console.log(lib);

    let container = document.querySelector('main') || document.getElementById('use');
    container.innerHTML = '<div class="bd-intro">' +
        '<button id="test-tooltip" type="button" class="btn btn-lg btn-danger" data-bs-toggle="tooltip" title="Tooltip title">Click to toggle Tooltip</button>\n' +
        '</div>' + container.innerHTML;
    let element = document.querySelector('#test-tooltip');
    element.parentNode.style.position = 'relative';
    new lib.Tooltip(element, {container: element.parentNode});
})();
```
![image](https://user-images.githubusercontent.com/26907947/107476522-d1431400-6b97-11eb-98d1-e30143beace7.png)
![image](https://user-images.githubusercontent.com/26907947/107476572-eddf4c00-6b97-11eb-8c57-83003d742586.png)

**Comment by thednp** [comment]
Hey man.

As you know our components use a `.fixed-navbar[-top|botttom]` || .`modal` || `document.body` as the default container option. They won't check in the DOM tree if there is another type of container other than these, except the option you set yourself.

However, viewing this from another angle, this might actually be a better solution, to check the first `position-relative` parent in the DOM tree as a replacement for the above element types.

**Comment by thednp** [comment]
I see, I will look into it asap, we might have to rework the `styleTip` utility, but I don't see a good reason to add a tooltip / popover in other container other than document.body / modal/ fixed-navbar.

**Comment by cvaize** [comment]
I think getting a container from which the indent will be calculated based on checking `position-relative`, `position-absolute`, `position-sticky` is a good idea. I came across this when I was making Popover-based pop-up filters inside a form. 
![image](https://user-images.githubusercontent.com/26907947/107485608-cee7b680-6ba5-11eb-9ff2-76fe871008f7.png)

**Comment by cvaize** [comment]
I want to add that `container` will not work because of `position` in 90% of cases if it is not fixed. 😰

**Comment by thednp** [comment]
I'm working a solution for this, however I'm scratching my head to understand why you would need a `position:relative` container for tooltips / popovers? In most cases our code works flawless, why use containers like that makes little sense to me. 

Can you provide a codepen and a reasonable explaination to why this should work this way?

**Comment by thednp** [comment]
@cvaize please test latest code in master. New tooltips / popovers settings added to use a position: relative container in the demo page.

Also #403 was solved, if you can check that as well, that would be awesome.

Thanks

**Comment by cvaize** [comment]
Unfortunately, you forgot about the other values, I think it is correct to use the expression `position !=="static"`.

![image](https://user-images.githubusercontent.com/26907947/107675207-ab159500-6cb9-11eb-9189-a4f3064f7586.png)

Checking and calculating the indent relative to the container is necessary because we use the `top` and `left` properties, which are relative to the `position` property. And when we specify any other container that has `position !=="static"`, our Popover and Tooltip are positioned incorrectly.

https://developer.mozilla.org/en-US/docs/Web/CSS/position

**Comment by thednp** [comment]
Can you get a screenshot with good values and bad values?

**Comment by thednp** [comment]
Alright, I think we have it, please check latest master and let me know.

**Comment by cvaize** [comment]
Again, there's more to come. By placing the tooltip in a container, this container can contain `position: static`, but above the container there can be an element with `position !== static`.

Here is a sample code.

```javascript
(function (){
    let lib = window.bootstrap || window.BSN;
    console.log(lib);

    let container = document.querySelector('main') || document.getElementById('use');
    container.innerHTML = '<div class="wrapper-relative" style="position:relative;padding: 100px;"><div id="test-tooltip-container" class="container" style="position:static;">' +
        '<button id="test-tooltip" type="button" class="btn btn-lg btn-danger" data-bs-toggle="tooltip" title="Tooltip title">Click to toggle Tooltip</button>\n' +
        '</div></div>' + container.innerHTML;
    let element = document.querySelector('#test-tooltip');
    new lib.Tooltip(element, {container: document.querySelector('#test-tooltip-container')});
})();
```

![image](https://user-images.githubusercontent.com/26907947/107735075-aa641980-6d20-11eb-9b4e-229a533b1c00.png)

**Comment by thednp** [comment]
You do realize there is an entire Popper.js to do all this calculation, we just haven't reached all cases yet.

**Comment by thednp** [comment]
@cvaize I've worked for some time on this issue and I made Popover/Tooltip work with relative container and/or absolute/relative positioned target button, with Media elements compliance, but I haven't found a solution for every kind of markup structure.

In the example you've showcased above, you have to use the `<div class="wrapper-relative">` with `position: relative` as container for your tooltips, our script cannot and should not go up the DOM tree when a container with `position: static` is set, let me explain why:

* we can only guess what's above the static container, which is not a desirable outcome for the community at large;
* we need to compute tooltip position based on target offsets or bounding rect, depending on what's the container and the markup structure;
* our `styleTip` has to be super simple and real fast, we cannot look up the DOM tree this on every `mousemove` from our implementation with Media elements; and also we cannot store this data on init because it will be incorrect on first resize/scroll
* another way we might deal with this static container is to actually override the user setting to either first relative parent found, or the `<body>`

So, the best thing to do is to set a container that has `position: relative`, it's probably the easiest way to handle Popover/Tooltip position in correlation with its target (button) parents and container setting without Popper.js.

Let me know if that's good enough, I will commit the latest code to the master as soon as possible.

**Comment by thednp** [comment]
@cvaize check the demo.

**Comment by thednp** [comment]
@cvaize come on buddy, I need your confirmation :D

**Comment by cvaize** [comment]
I confirm that everything is working properly! =) Thank you very much!
