### ISSUE TITLE
Close dropdowns on escape / click outside

### ISSUE THREAD

**Issue by warreb1** [thednp/bootstrap.native#44]
Is there a way to close the dropdown when clicking anywhere/pressing escape?

**Comment by thednp** [comment]
It already closes on focus out, but not on `ESC` key.

**Comment by warreb1** [comment]
Hmm. It doesn't over here -> http://sendvid.com/kyizc0dk
Any idea on this matter? It's a standard implementation.

`<li class="blocks__block__actions-listitem dropdown">
				<button type="button" class="button button--border button--white button--icon button--small button--round" id="add-to-a-trip-dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"><i class="mdi mdi-plus"></i></button>
				<ul class="dropdown-menu dropdown-menu--center" aria-labelledby="add-to-a-trip-dropdown">
					<li class="dropdown-menu__title">Add to a trip</li>
				    <li class="dropdown-menu__cta"><a href="#">Lorem ipsum dolor. Roadtrip Italy</a></li>
				    <li class="dropdown-menu__cta"><a href="#">Scandinavia</a></li>
				    <li class="dropdown-menu__cta"><a href="#">USA</a></li>
				    <li role="separator" class="dropdown-menu__divider"></li>
				    <li class="dropdown-menu__cta dropdown-menu__cta--alt"><a href="#">+ Create new</a></li>
				</ul>
			</li>`

**Comment by thednp** [comment]
Make sure the `data-toggle="dropdown"` element is not targeted by other function as in my demo there is no such issue.

**Comment by warreb1** [comment]
In Chrome it works indeed, but not in Safari nor Firefox (doesn't work in the demo ether).

**Comment by thednp** [comment]
I confirm the issue on Safari (Win). I will have a look asap.

**Comment by thednp** [comment]
Since I am not able to test on Safari please help me fix it:
* Create a local copy of the demo, 
* only add the `dropdown.js` file to the demo
* change [this line](https://github.com/thednp/bootstrap.native/blob/master/lib/dropdown-native.js#L39) to this
```javascript
self.menu.addEventListener('focusout', self.close, false);
```

Let me know if that fixes the issue on both Safari and Firefox.
Thank you

**Comment by warreb1** [comment]
Sadly no. The close function is not fired in Safari or Firefox.

**Comment by thednp** [comment]
OK, I'll look into it ASAP.

**Comment by thednp** [comment]
Please have  little time and test all plugins and report back any issue you can find on you MAC, I really want to solve all of the issues.

**Comment by warreb1** [comment]
Very well. I'll go over everything during the weekend.

**Comment by thednp** [comment]
Thanks so much.

**Comment by warreb1** [comment]
In the Tab section the first dropdown cannot be closed in Safari (Mac), yet the second dropdown (in the changing content) can be closed when clicking outside of it. So it works over there tho, but nowhere else.

**Comment by thednp** [comment]
I opened Safari 5.1 for Win and I can see 

`ReferenceError: Can't find variable: Window` which means the `Window` polyfil is missing, I think this must be the cause in my computer, but not sure about yours.

Please also report any error in your log

**Comment by warreb1** [comment]
I don't get any error, but if the window polyfill isn't working, that might be the cause indeed.

**Comment by thednp** [comment]
I see, perhaps your Safari version is latest and there is no error anyway.

**Comment by thednp** [comment]
Please check if the dropdowns in the [right side](http://thednp.github.io/bootstrap.native/#exampleDropdown) also don't close on clicking outside.

**Comment by warreb1** [comment]
Yes, both the one with the label "pill" and the label "dropdown" on the right close on clicking outside.

**Comment by thednp** [comment]
Good, in that case I have to check original plugins, perhaps there is something I missed with HTML specific attributes in the demo.

**Comment by thednp** [comment]
**Update**: I think this must be due to the fact that not all elements support `blur` and `focusout`, as the first 2 examples in the left side are both of type `<button>` and they may not support those types of events or the events have been implemented incomplete into the Safari browser. 
[Check this for a reference](http://www.quirksmode.org/dom/events/blurfocus.html). I'll see if I can find a fix for that.

**Comment by thednp** [comment]
**Final Update**
The issue is completely busted. I also implemented `Esc` dismiss.

**Comment by warreb1** [comment]
Busted in terms of "it works now"? I tried the demo but still the same.. (esc doesn't work ether) or is the demo not updated yet? 

The Esc dismiss is not triggered on chrome ether.

**Comment by thednp** [comment]
Yes, the demo is not yet updated, I only committed to the master so far, once I finish updating the doc. Please download files from master repo and test them on your device.

**Comment by thednp** [comment]
Please check demo and the updated doc.

**Comment by warreb1** [comment]
Alright works perfectly! GJ man!

**Comment by thednp** [comment]
Alrighty, CDN updated, soon npm as well.
